language: ruby
cache: bundler
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.0"
  - "2.5.3"
gemfile:
  - "gemfiles/delayed_job_3.gemfile"
  - "gemfiles/delayed_job_4.gemfile"
matrix:
  exclude:
  - rvm: "2.5.3"
    gemfile: "gemfiles/delayed_job_3.gemfile"
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
